name: Build and release dictionary for Fcitx5 and RIME

on:
  schedule:
    - cron: '30 0 1 * *'
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Environment for Build
        run: |
          wget https://github.com/studyzy/imewlconverter/releases/download/preview/imewlconverter_Linux.tar.gz
          tar -zxf imewlconverter_Linux.tar.gz

      - name: Build
        run: |
          echo "${GITHUB_WORKSPACE}/publish" >> "$GITHUB_PATH"
          ImeWlConverterCmd
